---
- hosts: ubuntu
  become: yes
  become_user: root
  tasks:

    - name: DB erzeugen
      docker_container:
        name: heimdatenbank
        image: mysql
        state: started
        ports:
          - 192.168.178.101:3000:3306
        env:
          MYSQL_ROOT_PASSWORD: Schmetterl1ng
          MYSQL_DATABASE: wordpress
        volumes:
          heimwebsite:/var/lib/mysql

    - name: WP erzeugen
      docker_container:
        name: heimwebserver
        image: wordpress
        state: started
        ports:
          - 192.168.178.99:8000:80
        env:
          WORDPRESS_DB_HOST: heimdatenbank
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: Schmetterl1ng
        volumes:
          - wp-heimwebsite:/var/www/html
        links:
          - heimdatenbank:mysql

    - name: PHP erzeugen
      docker_container:
        name: heimphpserver
        image: phpmyadmin
        state: started
        ports:
          - 192.168.178.99:12000:80
        env:
          PMA_HOST: heimdatenbank
        links:
          - heimdatenbank:mysql
