---
- hosts: all
  become: yes
  tasks:
    - name: Datenbank erzeugen
      docker_container:
        name: backend
        image: mysql:latest
        state: started
        ports:
          - 192.168.56.104:3305:3306
        env:
          MYSQL_ROOT_PASSWORD: Schmetterl1ng
        volumes:
          - website:/var/lib/mysql

    - name: Wordpress erzeugen
      docker_container:
        name: frontend
        image: wordpress:latest
        state: started
        ports: 
          - 192.168.56.104:80:80
        env:
          WORDPRESS_DB_HOST: backend
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_PASSWORD: Schmetterl1ng
        volumes:
          - wp-website:/var/www/html
        links:
          - backend:mysql

    - name: PHPmyAdmin erzeugen
      docker_container:
        name: uebersicht
        image: phpmyadmin:latest
        state: started
        ports:
          - 192.168.56.104:88:80
        env:
          PMA_HOST: backend
        links:
          - backend:mysql
