---
- hosts: all
  become: yes
  tasks:

    - name: lösche php-server
      docker_container:
        name: uebersicht
        image: phpmyadmin
        state: absent
        force_kill: true

    - name: lösche webserver
      docker_container:
        name: frontend
        image: wordpress
        state: absent
        force_kill: true
     
    - name: lösche Datenbank
      docker_container:
        name: backend
        image: mysql
        state: absent
        force_kill: true
