---
- hosts: all
  become: yes
  tasks:

    - name: Datenbank-Container erzeugen
      docker_container:
        name: Z18_datenbank
        image: mysql
        state: started
        ports:
          - 192.168.18.101:3000:3306
        volumes:
          - Z18-website:/var/lib/mysql
        env:
          MYSQL_ROOT_PASSWORD: michaeloderjörg

    - name: Wordpress-Container erzeugen 
      docker_container:
        name: Z18_webserver
        image: wordpress
        state: started
        ports: 
          - 192.168.18.99:80:80
        env:
          WORDPRESS_DB_HOST: Z18_datenbank
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: Schmetterl1ng
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - wp-Z18-website:/var/www/html              
        links:
          - Z18_datenbank:mysql  
  
    - name: PHPmyAdmin-Container erzeugen
      docker_container:
        name: Z18_phpserver
        image: phpmyadmin
        state: started
        ports:
          - 192.168.18.99:12000:80
        env:
          PMA_HOST: Z18_datenbank
        links:
          - Z18_datenbank:mysql
