---
- hosts: all
  become: yes
  tasks:

    - name: Datenbank-Container erzeugen
      docker_container:
        name: Z19_datenbank
        image: mysql
        state: started
        ports:
          - 192.168.19.101:80:3306
        volumes:
          - Z19-website:/var/lib/mysql
        env:
          MYSQL_ROOT_PASSWORD: Schmetterl1ng

    - name: Wordpress-Container erzeugen 
      docker_container:
        name: Z19_webserver
        image: wordpress
        state: started
        ports: 
          - 192.168.19.99:8000:80
        env:
          WORDPRESS_DB_HOST: Z19_datenbank
          WORDPRESS_DB_USER: root
          WORDPRESS_DB_PASSWORD: Schmetterl1ng
          WORDPRESS_DB_NAME: wordpress
        volumes:
          - wp-Z19-website:/var/www/html               
        links:
          - Z19_datenbank:mysql  
     
    - name: PHPmyAdmin-Container erzeugen
      docker_container:
        name: Z19_phpserver
        image: phpmyadmin
        state: started
        ports:
          - 192.168.19.99:12000:80
        env:
          PMA_HOST: Z19_datenbank
        links:
          - Z19_datenbank:mysql
